#!/usr/bin/env bash
# This script displays "To infinity and beyond"
# And "I am invicible!!!" when receiving a SIGTERM signal

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible"' SIGTERM 
done
